version: "3.9"

services:
  web:
    image: odoo:14
    build:
      context: .
    depends_on:
      - db
      - traefik
    command:
      - --addons-path=/mnt/addons/oca/web,
        /mnt/addons/oca/server-tools,
        /mnt/addons/oca/server-brand,
        /mnt/addons/oca/server-ux,
        /mnt/addons/oca/project,
        /mnt/addons/oca/partner-contact,
        /mnt/addons/oca/reporting-engine
      - --dev=all
      - --update=all
      - --db-filter=^%d.*$$
      - --i18n-overwrite
      - --max-cron-threads=0
    volumes:
      - ./addons:/mnt/extra-addons
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo.rule=HostRegexp(`{subdomain:[a-z]+}.{subdomain:[a-z]+}.localhost`, `{subdomain:[a-z]+}.localhost`)
      - traefik.http.routers.odoo.service=odoo
      - traefik.http.services.odoo.loadbalancer.server.port=8069
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${ODOO_USER}
      POSTGRES_PASSWORD: ${ODOO_PASS}
    restart: unless-stopped

  traefik:
    image: traefik:2.5
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  py3o:
    image: xcgd/py3o:1.0.0
    depends_on:
      - web
    restart: unless-stopped

  adminer:
    image: adminer:4
    depends_on:
      - db
      - traefik
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: "tables-filter tinymce"
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.service=adminer
      - traefik.http.routers.adminer.rule=Host(`localhost`) && (Path(`/adminer`))
      - traefik.http.services.adminer.loadbalancer.server.port=8080
    restart: unless-stopped