version: "3.9"

services:
  web:
    image: odoo:14
    build:
      context: .
    depends_on:
      - db
    command:
      - --addons-path=/mnt/addons/oca/web,
        /mnt/addons/oca/server-tools,
        /mnt/addons/oca/server-brand,
        /mnt/addons/oca/server-ux,
        /mnt/addons/oca/project,
        /mnt/addons/oca/partner-contact,
        /mnt/addons/oca/reporting-engine
      - --dev=all
      - --update=all
    volumes:
      - ./addons:/mnt/extra-addons
    ports:
      - 8069:8069
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${ODOO_USER}
      POSTGRES_PASSWORD: ${ODOO_PASS}
    restart: unless-stopped

  py3o:
    image: xcgd/py3o:1.0.0
    depends_on:
      - web
    restart: unless-stopped

  adminer:
    image: adminer:4
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: "tables-filter tinymce"
    ports:
      - 8080:8080
    restart: unless-stopped